// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	model "github.com/dwarvesf/go-api/pkg/model"
	mock "github.com/stretchr/testify/mock"
)

// Controller is an autogenerated mock type for the Controller type
type Controller struct {
	mock.Mock
}

type Controller_Expecter struct {
	mock *mock.Mock
}

func (_m *Controller) EXPECT() *Controller_Expecter {
	return &Controller_Expecter{mock: &_m.Mock}
}

// Login provides a mock function with given fields: req
func (_m *Controller) Login(req model.LoginRequest) (*model.LoginResponse, error) {
	ret := _m.Called(req)

	var r0 *model.LoginResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(model.LoginRequest) (*model.LoginResponse, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(model.LoginRequest) *model.LoginResponse); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.LoginResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(model.LoginRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Controller_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type Controller_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - req model.LoginRequest
func (_e *Controller_Expecter) Login(req interface{}) *Controller_Login_Call {
	return &Controller_Login_Call{Call: _e.mock.On("Login", req)}
}

func (_c *Controller_Login_Call) Run(run func(req model.LoginRequest)) *Controller_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.LoginRequest))
	})
	return _c
}

func (_c *Controller_Login_Call) Return(_a0 *model.LoginResponse, _a1 error) *Controller_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Controller_Login_Call) RunAndReturn(run func(model.LoginRequest) (*model.LoginResponse, error)) *Controller_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Signup provides a mock function with given fields: req
func (_m *Controller) Signup(req model.SignupRequest) error {
	ret := _m.Called(req)

	var r0 error
	if rf, ok := ret.Get(0).(func(model.SignupRequest) error); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Controller_Signup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Signup'
type Controller_Signup_Call struct {
	*mock.Call
}

// Signup is a helper method to define mock.On call
//   - req model.SignupRequest
func (_e *Controller_Expecter) Signup(req interface{}) *Controller_Signup_Call {
	return &Controller_Signup_Call{Call: _e.mock.On("Signup", req)}
}

func (_c *Controller_Signup_Call) Run(run func(req model.SignupRequest)) *Controller_Signup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.SignupRequest))
	})
	return _c
}

func (_c *Controller_Signup_Call) Return(_a0 error) *Controller_Signup_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Controller_Signup_Call) RunAndReturn(run func(model.SignupRequest) error) *Controller_Signup_Call {
	_c.Call.Return(run)
	return _c
}

// NewController creates a new instance of Controller. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewController(t interface {
	mock.TestingT
	Cleanup(func())
}) *Controller {
	mock := &Controller{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
