// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	orm "github.com/dwarvesf/go-api/pkg/repository/orm"
	mock "github.com/stretchr/testify/mock"
)

// Controller is an autogenerated mock type for the Controller type
type Controller struct {
	mock.Mock
}

type Controller_Expecter struct {
	mock *mock.Mock
}

func (_m *Controller) EXPECT() *Controller_Expecter {
	return &Controller_Expecter{mock: &_m.Mock}
}

// Me provides a mock function with given fields: userID
func (_m *Controller) Me(userID int) (*orm.User, error) {
	ret := _m.Called(userID)

	var r0 *orm.User
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*orm.User, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(int) *orm.User); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*orm.User)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Controller_Me_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Me'
type Controller_Me_Call struct {
	*mock.Call
}

// Me is a helper method to define mock.On call
//   - userID int
func (_e *Controller_Expecter) Me(userID interface{}) *Controller_Me_Call {
	return &Controller_Me_Call{Call: _e.mock.On("Me", userID)}
}

func (_c *Controller_Me_Call) Run(run func(userID int)) *Controller_Me_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *Controller_Me_Call) Return(_a0 *orm.User, _a1 error) *Controller_Me_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Controller_Me_Call) RunAndReturn(run func(int) (*orm.User, error)) *Controller_Me_Call {
	_c.Call.Return(run)
	return _c
}

// NewController creates a new instance of Controller. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewController(t interface {
	mock.TestingT
	Cleanup(func())
}) *Controller {
	mock := &Controller{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
