basePath: /api/v1
info:
  contact:
    email: andy@d.foundation
    name: Andy
    url: https://d.foundation
  description: This is api document for APP API project.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: APP API DOCUMENT
  version: v0.0.1
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
