// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// FinalFunc is an autogenerated mock type for the FinalFunc type
type FinalFunc struct {
	mock.Mock
}

type FinalFunc_Expecter struct {
	mock *mock.Mock
}

func (_m *FinalFunc) EXPECT() *FinalFunc_Expecter {
	return &FinalFunc_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0
func (_m *FinalFunc) Execute(_a0 error) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(error) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FinalFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type FinalFunc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 error
func (_e *FinalFunc_Expecter) Execute(_a0 interface{}) *FinalFunc_Execute_Call {
	return &FinalFunc_Execute_Call{Call: _e.mock.On("Execute", _a0)}
}

func (_c *FinalFunc_Execute_Call) Run(run func(_a0 error)) *FinalFunc_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(error))
	})
	return _c
}

func (_c *FinalFunc_Execute_Call) Return(_a0 error) *FinalFunc_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FinalFunc_Execute_Call) RunAndReturn(run func(error) error) *FinalFunc_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewFinalFunc creates a new instance of FinalFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFinalFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *FinalFunc {
	mock := &FinalFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
